const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const index=read('public/index.html');
const app=read('public/app.js');
const css=read('public/style.css');
const sw=read('public/sw.js');

test('Vestfjella identity and version are present',()=>{assert.match(index,/Vestfjella Fiske/);assert.match(index,/STABLE 1\.7/);});
test('mobile filter panel exists',()=>assert.match(index,/id="filterPanel"/));
test('freshwater species are limited to all, trout and perch',()=>{assert.match(index,/value="all"/);assert.match(index,/value="orret"/);assert.match(index,/value="abbor"/);assert.doesNotMatch(index,/value="sjoorret"/);});
test('access filter is preserved',()=>assert.match(index,/id="accessFilter"/));
test('map menu is simplified',()=>{assert.match(index,/Fiskekart – NVE dybder/);assert.match(index,/Detaljert topo/);assert.match(index,/3D bunn \/ terreng/);assert.match(index,/Satellitt/);assert.doesNotMatch(index,/Turkart/);assert.doesNotMatch(index,/Terrengskygge/);assert.doesNotMatch(index,/Standardkart/);assert.doesNotMatch(index,/Hybrid/);});
test('BiteGuide hook is in the app',()=>assert.match(app,/function biteGuideHtml/));
test('BiteGuide says the profile is independent from the own lure box',()=>assert.match(app,/UAVHENGIG AV DIN SLUKBOKS/));
test('automatic NVE freshwater overlay is wired',()=>{assert.match(app,/\/api\/freshwater-depth-overlay/);assert.match(app,/freshwaterDepthLayer/);});
test('NVE depth raster and contour labels are rendered',()=>{assert.match(app,/renderFreshwaterDepthRaster/);assert.match(app,/nve-depth-label/);});
test('3D freshwater bathymetry is wired',()=>{assert.match(app,/\/api\/bathymetry-grid/);assert.match(app,/water=freshwater/);assert.match(app,/function fetchBathymetryGrid/);});
test('known-water directory is visible',()=>{assert.match(index,/Kjente vann – beste først/);assert.match(app,/loadWaterDirectory\(\)/);});
test('known-water focus is wired',()=>assert.match(app,/data-water-focus/));
test('access filter affects zone list',()=>assert.match(app,/filterZonesByAccess/));
test('user lure catalog is loaded from Vestfjella catalog',()=>assert.match(app,/\/data\/user-lures\.json/));
test('Live GPS remains available',()=>{assert.match(index,/id="live"/);assert.match(app,/watchPosition/);});
test('service worker has Vestfjella cache',()=>assert.match(sw,/vestfjella-fiste2-stable-1-7/));
test('mobile CSS includes water directory responsive rules',()=>{assert.match(css,/#waterDirectory/);assert.match(css,/@media\(max-width:650px\)/);});
