const fs=require('fs');
const path=require('path');
const pkg=require('../package.json');
const root=path.resolve(__dirname,'..');
const pub=path.join(root,'public');
function must(cond,msg){if(!cond){console.error(`DEPLOY BLOCKED: ${msg}`);process.exit(1);}}
for(const name of ['index.html','app.js','style.css','sw.js','manifest.webmanifest']) must(fs.existsSync(path.join(pub,name)),`public/${name} mangler.`);
const index=fs.readFileSync(path.join(pub,'index.html'),'utf8');
const app=fs.readFileSync(path.join(pub,'app.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
const versionParts=String(pkg.version||'').split('.');
const stable=`STABLE ${versionParts[0]}.${versionParts[1]}`;
must(index.includes(stable),`public/index.html er ikke ${stable}.`);
must(index.includes('Fiskekart – NVE dybder'),'Fiskekart med automatisk NVE mangler.');
must(index.includes('Kjente vann – beste først'),'Vestfjella vannregister mangler i layout.');
must(index.includes('id="accessFilter"'),'Tilkomstfilter mangler.');
must(app.includes('/api/freshwater-depth-overlay'),'NVE dybdeoverlay er ikke koblet i app.js.');
must(app.includes('loadWaterDirectory()'),'Vannregisteret lastes ikke automatisk.');
must(app.includes('/sw.js?v=1.7'),'Feil service-worker-versjon i app.js.');
must(sw.includes('vestfjella-fiste2-stable-1-7'),'Feil cache-navn i service worker.');
must(sw.includes('/data/vestfjella-waters.json'),'Vestfjella-registeret caches ikke.');
console.log(`Layout OK: ${stable} · Fiste 2 / Vestfjella.`);
